version: '3.9'
### Author:vmn3

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminwordpress
      MYSQL_DATABASE: vmnwordpress
      MYSQL_USER: vmnwordpress
      MYSQL_PASSWORD: vmnwordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    #ports:
    # - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: vmnwordpress
      WORDPRESS_DB_PASSWORD: vmnwordpress
      WORDPRESS_DB_NAME: vmnwordpress

  nginx:
    depends_on: 
      - wordpress
    image: nginx:1.20-alpine
    restart: always
    command: "/bin/sh -c 'nginx -s reload; nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
    # - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d

volumes:
  db_data: {}
  wordpress_data: {}